name: Maven Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            unzip \
            fonts-liberation \
            libappindicator3-1 \
            libnss3 \
            libxss1 \
            libxtst6 \
            xdg-utils \
            libgbm-dev \
            libasound2 \
            libnspr4 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgtk-3-0 \
            libxshmfence1

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Generate Allure report
        run: mvn allure:report

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
